name: .NET Core Desktop

on:
  push:
    branches: ["master"]
    paths-ignore: ["**.md", "LICENSE"]

  pull_request:
    branches: ["master"]
    paths-ignore: ["**.md", "LICENSE"]

permissions:
  contents: write

jobs:

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
          - os: windows-latest
            runtime: win-x64
          - os: macos-latest
            runtime: osx-arm64
          - os: macos-15-intel
            runtime: osx-x64

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Generate version
        id: ver
        shell: bash
        run: echo "version=1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained true -p:PublishAot=true -p:DebugType=None -p:PublishTrimmed=true -p:DebugSymbols=false -o publish

      - name: Publish
        run: >
          dotnet publish
          -c Release
          -r ${{ matrix.runtime }}
          --self-contained true
          -p:PublishAot=true
          -p:PublishTrimmed=true
          -p:DebugType=None
          -p:DebugSymbols=false
          -p:StripSymbols=true
          -p:InvariantGlobalization=true
          -p:OptimizationPreference=Speed
          -p:UseSizeOptimizedLinq=true
          -o publish/out

      - name: Rename output
        shell: bash
        run: |
          mkdir -p dist

          if [[ "${{ matrix.runtime }}" == win-* ]]; then
            mv publish/out/Repeater.exe dist/Repeater-${{ matrix.runtime }}.exe
          else
            mv publish/out/Repeater dist/Repeater-${{ matrix.runtime }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Repeater-${{ matrix.runtime }}
          path: dist/


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Generate version
        id: ver
        run: echo "version=1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.ver.outputs.version }}
          name: Repeater v${{ steps.ver.outputs.version }}
          files: dist/**/*
